/*
 * bench.c
 *
 * Benchmark driver for measuring invert_matrix() instruction counts.
 *
 * Two problems with profiling the programs as they stand, both of which
 * this file solves:
 *
 *   1. Each program inverts one or two matrices and prints them. The
 *      printf work dwarfs the arithmetic, so a profile of the whole
 *      program is mostly a profile of the C library.
 *
 *   2. With a single call site, GCC can inline invert_matrix() straight
 *      into main(). Its cost then gets attributed to main() and
 *      callgrind reports nothing against invert_matrix.
 *
 * This driver lives in its own translation unit. Without -flto the
 * compiler cannot inline across that boundary, so invert_matrix() is
 * guaranteed to stay a real, separately-attributable function. It then
 * runs many inversions and prints nothing until the end.
 *
 * The matrix pool is generated by a fixed linear congruential
 * generator rather than rand(), so every build sees byte-for-byte
 * identical input. That matters: if the baseline and the NEON version
 * were fed different matrices, the comparison would be meaningless.
 *
 * Build (see the Makefile):
 *   gcc -c -Dmain=program_main not_optimized_fixedpoint.c -o base.o
 *   gcc -c bench.c -o bench.o
 *   gcc base.o bench.o -o bench_baseline
 *
 * The -Dmain=program_main renames the original file's main() out of the
 * way so this one can take over. Nothing in the source needs editing.
 */

#include <stdio.h>
#include <stdint.h>

#define N 8

#define MATRIX_SUCCESS 1

#ifndef ITERATIONS
#define ITERATIONS 1000
#endif

#define POOL_SIZE 64

/*
 * Declared, not defined. Supplied by whichever matrix source file is
 * linked in.
 */
extern int invert_matrix(const int16_t input[N][N], int16_t inverse[N][N]);

int main(void)
{
    static int16_t pool[POOL_SIZE][N][N];
    int16_t inverse[N][N];

    uint32_t state = 440u;
    long succeeded = 0;
    int index;
    int row;
    int column;

    /*
     * Deterministic pool. Values span the full Q4.12 range from -1.0 to
     * +1.0 (-4096 to +4096 in stored units), which is the input
     * normalization the specification assumes.
     */
    for (index = 0; index < POOL_SIZE; index++) {
        for (row = 0; row < N; row++) {
            for (column = 0; column < N; column++) {
                state = state * 1103515245u + 12345u;
                pool[index][row][column] =
                    (int16_t)((int32_t)((state >> 16) % 8193u) - 4096);
            }
        }
    }

    for (index = 0; index < ITERATIONS; index++) {
        if (invert_matrix(
                (const int16_t (*)[N])pool[index % POOL_SIZE],
                inverse) == MATRIX_SUCCESS) {
            succeeded++;
        }
    }

    printf("%d inversions attempted, %ld succeeded\n",
           ITERATIONS, succeeded);

    /*
     * Keep one result observable so the optimizer cannot discard the
     * loop entirely.
     */
    printf("last inverse[0][0] = %d\n", (int)inverse[0][0]);

    return 0;
}